version: "3.8"
name: "messenger-compose"

services:
  auth-service:
    ports:
      - "8081:8080"
    build:
      context: auth-service
      dockerfile: Dockerfile

  messaging-service:
    ports:
      - "8082:8080"
    build:
      context: messaging-service
      dockerfile: Dockerfile

  server-service:
    ports:
      - "8083:8080"
    build:
      context: server-service
      dockerfile: Dockerfile

  user-service:
    ports:
      - "8084:8080"
    build:
      context: user-service
      dockerfile: Dockerfile
